# Generated by Django 4.2.2 on 2023-06-24 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_customuser_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profile_images/'),
            preserve_default=False,
        ),
    ]
