# Generated by Django 4.2.2 on 2023-06-29 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='enattente',
            field=models.ManyToManyField(related_name='att_formations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formation',
            name='participants',
            field=models.ManyToManyField(related_name='par_formations', to=settings.AUTH_USER_MODEL),
        ),
    ]
