# Generated by Django 4.2.2 on 2023-06-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_formation_enattente_alter_formation_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='enattente',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='participants',
        ),
        migrations.AddField(
            model_name='formation',
            name='participants',
            field=models.JSONField(default=dict),
        ),
    ]
