# Generated by Django 4.2.2 on 2023-06-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0003_remove_formation_enattente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='titre',
            field=models.TextField(),
        ),
    ]
