# Generated by Django 3.2.6 on 2023-07-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0005_alter_formation_formateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='qr',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
